# Use Dockerized infrastructure
sudo: false

language: go
go:
  - master

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules

services:
  - docker

before_install:
  - go get

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME=brynn-145714
    - CLUSTER_NAME=cluster-1
    - CLOUDSDK_COMPUTE_ZONE=europe-west1-b
    - DOCKER_IMAGE_NAME=brynnse
    - K8S_NAMESPACE=brynnse
    - K8S_DEPLOYMENT_NAME_WEB=web
    - K8S_DEPLOYMENT_NAME_NGINX=nginx
    - COMMIT=${TRAVIS_COMMIT::7}

jobs:
  include:
    - stage: unit test js
      install: docker build -t node -f Dockerfile.node .
      script: docker run -it -v `pwd`/static:/build/static node:latest
    - stage: unit test go
      script: go test
    - stage: deploy
      before_deploy: ./devops/script/install-deploy-dependencies.sh
      deploy:
        - provider: script
          script: ./devops/script/deploy.sh
          skip_cleanup: true
          on:
            branch: master

notifications:
    email: false
    on_success: always
    on_failure: always
    slack:
      secure: Ry3mrAbhhuVcchNvxEUDBwnBeLi6zCAB5uwI5V0FE+FOdQXiXYsBQPUx+IMjV4Dyyl421S1JLRvFiKDJgy+bJfmASrRQgnw0M/ecl9ZSU6inbUDOUFqf5A2wuvLF/2pt9Rnfj2ZlX65LZJHlTA1vCiAP3XNB/GIBXOIOL2jafKw4CVT/gkH2zVOg1naIbKePXxk3sLmK6afo4rKWJb/lm7mwyIGWTKaYtcaxI4trz9FNt59A50OWCi5EOQSAb12uWZjM9ZEu3G3RhqNC60VPuR29wLIxMyyRqRTCYy3m93vnct+hj6r0T2r/mHTVnhuc4R7j8R7qNcq4wEGhqnqFkyceYTxh5oU/tq84fQBu+tWapMnOQhK+uVq49vLozx944qUa9mNwTBq15f1xAhPr7cMMnbFmuACPl2PgBLL8j6SZdOoGtTnicbi4kMEbz/ZSOPgUVV3aUZaMmhSFSAaIAKucAJYAYdHuRQdU969C0qHwsOgEIrZi7ct+G9oDT+r7RafNCf+400JEydU8QJNt72+FnRiQ5ndWIExXELco40F4cA26T0NEu9DtbxydlxY4ROYJeDRMsxR7eplTfJSetBRe1hESQEF6TgJ7xSTdaFmR4YpPosqx4A4YfhUydEWEH3EAHzjDR5apsJJkeyFF86TEyF7v3jmly0699FJwN2c=
