steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'bundle']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', '-z', 'js,css', 'static', 'gs://$PROJECT_ID/brynnse/$REVISION_ID/static']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'setmeta', '-h', 'Cache-Control:public, max-age=31536000', 'gs://$PROJECT_ID/brynnse/$REVISION_ID/static/**']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'build', '-f', 'Dockerfile.build', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace':/go/src/github.com/larsha/brynn.se-go', '-w', '/go/src/github.com/larsha/brynn.se-go', 'build']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'STATIC=https://storage.googleapis.com/$PROJECT_ID/brynnse/$REVISION_ID/static', '-t', 'eu.gcr.io/$PROJECT_ID/brynnse/web:$REVISION_ID', '-t', 'eu.gcr.io/$PROJECT_ID/brynnse/web:latest', '-f', 'Dockerfile.prod', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/brynnse/web:$REVISION_ID']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/brynnse/web:latest']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['-n', 'brynnse', 'set', 'image', 'deployment/web', 'web=eu.gcr.io/$PROJECT_ID/brynnse/web:$REVISION_ID']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
