steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'bundle']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', '-z', 'js,css', 'static', 'gs://$PROJECT_ID/brynnse/$REVISION_ID/static']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'setmeta', '-h', 'Cache-Control:public, max-age=31536000', 'gs://$PROJECT_ID/brynnse/$REVISION_ID/static/**']

- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', '.build/ca-certificates.crt', 'https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt']

- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-a', '-installsuffix', 'cgo', '-o', '.build/main', '.']
  env:
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'STATIC=https://storage.googleapis.com/$PROJECT_ID/brynnse/$REVISION_ID/static', '-t', 'eu.gcr.io/$PROJECT_ID/brynnse/web:$REVISION_ID', '-t', 'eu.gcr.io/$PROJECT_ID/brynnse/web:latest', '-f', 'Dockerfile.scratch', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['docker', '--', 'push', 'eu.gcr.io/$PROJECT_ID/brynnse/web:$REVISION_ID']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['docker', '--', 'push', 'eu.gcr.io/$PROJECT_ID/brynnse/web:latest']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['-n', 'brynnse', 'set', 'image', 'deployment/web', 'web=eu.gcr.io/$PROJECT_ID/brynnse/web:$REVISION_ID']
