version: '2'
services:
  assets:
    build:
      context: .
      dockerfile: Dockerfile.assets
    command: sass /static/scss/main.scss /static/css/style.css --style compressed --sourcemap=none
    volumes:
      - ./static/scss:/static/scss
      - ./static/css:/static/css
