FROM golang:1.8

COPY . /go/src/github.com/larsha/brynn.se-go
WORKDIR /go/src/github.com/larsha/brynn.se-go

RUN go get ./
RUN go get -u -v github.com/codeskyblue/fswatch

CMD ["fswatch"]

EXPOSE 3000
