apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: brynnse
spec:
  revisionHistoryLimit: 2
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: nginx
        image: eu.gcr.io/brynn-145714/brynnse/nginx:latest
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "30"]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 1
          successThreshold: 1
          failureThreshold: 1
