apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: brynn
  namespace: brynnse
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/service-upstream: "true"
spec:
  tls:
  - secretName: brynn-tls
    hosts:
      - brynn.se
      - www.brynn.se
  rules:
  - host: brynn.se
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 3000
  - host: www.brynn.se
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 3000
