apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: frela
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "frela-ipv4"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: frela-tls
    hosts:
      - brynn.se
      - www.brynn.se
      - www.fredriklack.se
      - fredriklack.se
      - fre.la
      - www.fre.la
  rules:
  - host: www.fre.la
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 8081
  - host: fre.la
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 8081
  - host: brynn.se
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 8081
  - host: fredriklack.se
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 8081
  - host: www.fredriklack.se
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 8081
  - host: www.brynn.se
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 8081
