apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: brynnse
spec:
  revisionHistoryLimit: 2
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web
              topologyKey: kubernetes.io/hostname
      containers:
      - name: web
        image: eu.gcr.io/brynn-145714/brynnse/web:latest
        imagePullPolicy: Always
        env:
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: app_env
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: port
          - name: MAILGUN_EMAIL
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: mailgun_email
          - name: MAILGUN_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: mailgun_domain
          - name: MAILGUN_API_KEY
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: mailgun_api_key
          - name: MAILGUN_PUBLIC_API_KEY
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: mailgun_public_api_key
        ports:
        - containerPort: 3000
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 10
          timeoutSeconds: 1
        lifecycle:
          preStop:
            httpGet:
              path: /prestop
              port: 3001
